spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sistema_eventos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always